[package]
name = "num_rs_napi"
version = "0.1.0"
edition = "2021"

[features]
default = ["linalg"]
linalg = ["num_rs_core/linalg"]
cpu-openblas = ["num_rs_core/cpu-openblas"]
cpu-blis = ["num_rs_core/cpu-blis"]
cpu-mkl = ["num_rs_core/cpu-mkl"]
parallel = ["num_rs_core/parallel"]
gpu = ["num_rs_core/gpu"]
gpu-cuda = ["gpu", "num_rs_core/gpu-cuda"]
gpu-rocm = ["gpu", "num_rs_core/gpu-rocm"]

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", features = ["napi6"] }
napi-derive = "2"
ndarray = "0.15"
num_rs_core = { path = "../core-rs" }

[build-dependencies]
cc = "1"
napi-build = "2"
