[package]
name = "num_rs_core"
version = "0.1.0"
edition = "2021"

[features]
default = ["linalg", "npy"]
linalg = ["nalgebra"]
npy = ["ndarray-npy"]

[dependencies]
cfg-if = "1"
ndarray = { version = "0.15", features = ["std"] }
nalgebra = { version = "0.33", optional = true, features = ["serde-serialize", "std"] }
ndarray-npy = { version = "0.8", optional = true }
