[package]
name = "num_rs_core"
version = "0.1.0"
edition = "2021"

[features]
default = ["linalg"]
linalg = ["nalgebra"]

[dependencies]
cfg-if = "1"
ndarray = { version = "0.15", features = ["std"] }
nalgebra = { version = "0.33", optional = true, features = ["serde-serialize", "std"] }
ndarray-npy = "0.8"
