[package]
name = "num_rs_core"
version = "0.1.0"
edition = "2021"

[features]
default = ["linalg", "npy", "parallel"]
linalg = ["nalgebra"]
npy = ["ndarray-npy"]
cpu-openblas = ["dep:cblas", "dep:openblas-src"]
cpu-blis = ["dep:cblas", "dep:blis-src"]
cpu-mkl = ["dep:cblas", "dep:intel-mkl-src", "intel-mkl-src/mkl-static-lp64-iomp"]
parallel = ["dep:rayon"]
gpu = []
gpu-cuda = [
    "gpu",
    "dep:cudarc",
    "dep:once_cell",
    "cudarc/cuda-version-from-build-system",
]
gpu-rocm = ["gpu"]

[dependencies]
cfg-if = "1"
ndarray = { version = "0.15", features = ["std"] }
nalgebra = { version = "0.33", optional = true, features = ["serde-serialize", "std"] }
ndarray-npy = { version = "0.8", optional = true }
num-traits = "0.2"
py_literal = "0.4"
zip = { version = "0.5", default-features = false, features = ["deflate"] }
cblas = { version = "0.5", optional = true }
openblas-src = { version = "0.10", optional = true, default-features = false, features = ["cblas"] }
blis-src = { version = "0.2", optional = true, default-features = false, features = ["cblas"] }
intel-mkl-src = { version = "0.8", optional = true, default-features = false }
rayon = { version = "1.10", optional = true }
cudarc = { version = "0.11", optional = true, default-features = false, features = ["driver", "nvrtc"] }
once_cell = { version = "1.19", optional = true }
rustfft = "6"

[dev-dependencies]
proptest = "1"
