[package]
name = "num_rs_core"
version = "0.2.0"
edition = "2021"
build = "build.rs"

[features]
default = ["linalg", "npy", "parallel"]
linalg = ["nalgebra"]
npy = ["ndarray-npy"]
cpu-openblas = ["dep:cblas", "dep:openblas-src"]
cpu-blis = ["dep:cblas", "dep:blis-src"]
cpu-mkl = ["dep:cblas", "dep:intel-mkl-src", "intel-mkl-src/mkl-static-lp64-iomp"]
parallel = ["dep:rayon"]
gpu = []
gpu-cuda = [
    "gpu",
    "dep:cudarc",
    "dep:once_cell",
    "dep:half",
    "cudarc/cuda-version-from-build-system",
    "cudarc/cublaslt",
    "cudarc/f16",
]
gpu-rocm = ["gpu"]
sparse-native = ["sprs"]
sparse-suitesparse = []

[dependencies]
cfg-if = "1"
ndarray = { version = "0.15", features = ["std"] }
nalgebra = { version = "0.33", optional = true, features = ["serde-serialize", "std"] }
ndarray-npy = { version = "0.8", optional = true }
num-traits = "0.2"
py_literal = "0.4"
zip = { version = "0.5", default-features = false, features = ["deflate"] }
cblas = { version = "0.5", optional = true }
openblas-src = { version = "0.10", optional = true, default-features = false, features = ["cblas"] }
blis-src = { version = "0.2", optional = true, default-features = false, features = ["cblas"] }
intel-mkl-src = { version = "0.8", optional = true, default-features = false }
rayon = { version = "1.10", optional = true }
cudarc = { version = "0.17.3", optional = true, default-features = false, features = ["driver", "nvrtc", "cublas", "cublaslt", "dynamic-linking", "f16"] }
once_cell = { version = "1.19", optional = true }
half = { version = "2.3", optional = true }
rustfft = "6"
sprs = { version = "0.11", optional = true }

[dev-dependencies]
proptest = "1"
criterion = { version = "0.5", features = ["html_reports"] }

[build-dependencies]
cc = "1"

[[example]]
name = "sparse_poc"
required-features = ["sparse-native"]

[[bench]]
name = "sparse"
harness = false

[[bench]]
name = "gpu_vs_cpu"
harness = false
